version: 2

models:
  - name: stg_trips
    description: "Staging table for Austin bike share trips - cleaned and standardized from raw data"
    columns:
      - name: trip_id
        description: "Unique identifier for each trip"
        tests:
          - unique
          - not_null
  - name: stg_stations
    description: :"stations"
    columns:
      - name: station_id 
        tests:
          - unique
          - not_null
          